[build]
  command = "gulp build"
  publish = "./"
  functions = "functions"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "6.14.4"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
